//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string JobNature { get; set; }
        public string Channel { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public string EducationLevel { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
    }
}
